// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg3zFy1hvmiq0gzF1U52j0iSkTznD0IzI',
    appId: '1:1028604524203:web:f8ed8a63d5cb39bb6669ee',
    messagingSenderId: '1028604524203',
    projectId: 'tickpocket-f094e',
    authDomain: 'tickpocket-f094e.firebaseapp.com',
    storageBucket: 'tickpocket-f094e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkp0JrG2wp2cGXl-EmNyQhU_mVrFA4Q18',
    appId: '1:1028604524203:android:3ed8339f77d35e1d6669ee',
    messagingSenderId: '1028604524203',
    projectId: 'tickpocket-f094e',
    storageBucket: 'tickpocket-f094e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnCTlXbkmiH0OYTibE8NaAftJy-FTk6s',
    appId: '1:1028604524203:ios:13ff17e97ae8b60a6669ee',
    messagingSenderId: '1028604524203',
    projectId: 'tickpocket-f094e',
    storageBucket: 'tickpocket-f094e.appspot.com',
    iosBundleId: 'com.example.tickpocketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnCTlXbkmiH0OYTibE8NaAftJy-FTk6s',
    appId: '1:1028604524203:ios:d1e24ca86971c79c6669ee',
    messagingSenderId: '1028604524203',
    projectId: 'tickpocket-f094e',
    storageBucket: 'tickpocket-f094e.appspot.com',
    iosBundleId: 'com.example.tickpocketApp.RunnerTests',
  );
}
